### ISSUE TITLE
support arrays

### ISSUE THREAD

**Issue by derhuerst** [bendrucker/obj-query#1]
I need to querystringify data into the following format. It would be great if this library supported this.

```js
{
	'passengers[0][type]': 'A',
	'travels[0][id]': 'outbound-20170328',
	'travels[0][direction]': 'outward',
	'travels[0][date]': '2017-03-28',
	'travels[1][id]': 'outbound-20170329',
	'travels[1][direction]': 'outward',
	'travels[1][date]': '2017-03-29'
}
```

Would you mind a PR?

Update: There is [`q-flat`](https://github.com/DylanPiercey/q-flat), which doesn't have Travis and is missing a `test` script, but seems to be working fine otherwise.

**Comment by bendrucker** [comment]
Hmm I guess simple array support is ok. I honestly can't remember why I originally wrote this. There are other heavier packages like qs that support this. Not sure how much it makes sense to enhance this versus recommending other packages for more complete/complex uses.

**Comment by derhuerst** [comment]
Then let's but a link to `q-flat` in the readme.

**Comment by bendrucker** [comment]
You're welcome to send a PR with a `See also` section with links to other packages. qs belongs on the list as well. It has extra features for safely handling untrusted user input.
